apiVersion: apps/v1
kind: Deployment
metadata:
  name: SRVC_NAME-deployment
  labels:
    app: SRVC_NAME
    environment: production
    version: SEMVER
spec:
  replicas: 2
  selector:
    matchLabels:
      app: SRVC_NAME
  template:
    metadata:
      labels:
        app: SRVC_NAME
        version: SEMVER
    spec:
      containers:
      - name: SRVC_NAME
        image: DOCKER_HOST_URI/SRVC_NAME:SEMVER
        imagePullPolicy: Always
        ports:
        - containerPort: 5009
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "4Gi"
            cpu: "500m"
