--©2024, Ovais Quraishi
CREATE DATABASE zollama; 

--Create Tables
CREATE TABLE IF NOT EXISTS patient_notes (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
	patient_note_id TEXT UNIQUE NOT NULL,
    patient_id TEXT NOT NULL,
    patient_note JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS patient_documents (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
	patient_document_id TEXT UNIQUE NOT NULL,
    patient_id TEXT NOT NULL,
    patient_note_id TEXT NOT NULL,
    analysis_document JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS patient_codes (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
	patient_id TEXT NOT NULL,
    patient_document_id TEXT NOT NULL,
	codes_document JSONB NOT NULL
);

--Create Indexes
--Patient Codes
CREATE INDEX idx_timestamp ON patient_codes (timestamp);
CREATE INDEX idx_patient_id ON patient_codes (patient_id);
CREATE INDEX idx_patient_document_id ON patient_codes (patient_document_id);
CREATE INDEX idx_codes_document_gin ON patient_codes USING GIN (codes_document);

--Patient Notes
CREATE INDEX IF NOT EXISTS patient_note_id_index ON patient_notes (patient_note_id);
CREATE INDEX IF NOT EXISTS patient_id_index ON patient_notes (patient_id);
CREATE INDEX IF NOT EXISTS timestamp_index ON patient_notes (timestamp);
CREATE INDEX IF NOT EXISTS patient_note_gin_index ON patient_notes USING gin(patient_note jsonb_path_ops);
--Patient Documents
CREATE INDEX IF NOT EXISTS patient_document_id_index ON patient_documents (patient_document_id);
CREATE INDEX IF NOT EXISTS patient_id_index ON patient_documents (patient_id);
CREATE INDEX IF NOT EXISTS patient_note_id_index ON patient_documents (patient_note_id);
CREATE INDEX IF NOT EXISTS timestamp_index ON patient_documents (timestamp);
CREATE INDEX IF NOT EXISTS analysis_document_gin_index ON patient_documents USING gin(analysis_document jsonb_path_ops);
