--©2024, Ovais Quraishi
CREATE DATABASE reddit; 

--Create Tables
CREATE TABLE IF NOT EXISTS author (
        author_id VARCHAR PRIMARY KEY,
        author_name VARCHAR,
        author_created_utc INT
    );

CREATE TABLE IF NOT EXISTS post (
    post_id VARCHAR PRIMARY KEY,
    subreddit VARCHAR,
    post_author VARCHAR,
    post_title TEXT,
    post_body TEXT,
    post_created_utc INT,
    is_post_oc BOOLEAN,
    is_post_video BOOLEAN,
    post_upvote_count INTEGER,
    post_downvote_count INTEGER,
    subreddit_members INTEGER
);

CREATE TABLE IF NOT EXISTS comment (
    comment_id VARCHAR PRIMARY KEY,
    comment_author VARCHAR,
    is_comment_submitter BOOLEAN,
    is_comment_edited TEXT,
    comment_created_utc INT,
    comment_body text,
    post_id VARCHAR,
    subreddit TEXT
);

CREATE TABLE IF NOT EXISTS errors (
    item_id VARCHAR,
    item_type VARCHAR,
    error TEXT
);

CREATE TABLE IF NOT EXISTS subscription (
        datetimesubscribed VARCHAR,
        subreddit VARCHAR
);

CREATE TABLE IF NOT EXISTS analysis_documents (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    shasum_512 TEXT UNIQUE,
    analysis_document JSONB NOT NULL
); 

CREATE TABLE IF NOT EXISTS patient_documents (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    patient_id TEXT NOT NULL,
    analysis_document JSONB NOT NULL
);


--Create Indexes
CREATE UNIQUE INDEX IF NOT EXISTS analysis_documents_pkey ON public.analysis_documents USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS analysis_documents_shasum_512_key ON public.analysis_documents USING btree (shasum_512);
CREATE INDEX IF NOT EXISTS analysis_documents_patiend_id ON public.patient_documents USING btree (patient_id);
CREATE UNIQUE INDEX IF NOT EXISTS author_pkey ON public.author USING btree (author_id);
CREATE UNIQUE INDEX IF NOT EXISTS comment_pkey ON public.comment USING btree (comment_id);
CREATE INDEX IF NOT EXISTS comment_post_id_idx ON public.comment USING btree (post_id, subreddit);
CREATE INDEX IF NOT EXISTS errors_item_id_idx ON public.errors USING btree (item_id);
CREATE UNIQUE INDEX IF NOT EXISTS post_pkey ON public.post USING btree (post_id);
CREATE INDEX IF NOT EXISTS post_post_author_idx ON public.post USING btree (post_author);
CREATE INDEX IF NOT EXISTS post_subreddit_idx ON public.post USING btree (subreddit);
CREATE INDEX IF NOT EXISTS subscription_subreddit_idx ON public."subscription" (subreddit);
